/// Flutter icons LogOut
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LogOut
///      fonts:
///       - asset: fonts/LogOut.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
///
import 'package:flutter/widgets.dart';

class LogOut {
  LogOut._();

  static const _kFontFam = 'LogOut';
  static const String? _kFontPkg = null;

  static const IconData logout =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
