/// Flutter icons SleepReport
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SleepReport
///      fonts:
///       - asset: fonts/SleepReport.ttf
///
///
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class SleepReport {
  SleepReport._();

  static const _kFontFam = 'SleepReport';
  static const String? _kFontPkg = null;

  static const IconData graph =
      IconData(0xf35a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
